# Generated by Django 5.1.1 on 2024-10-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0002_remove_stock_created_at_stock_beta_stock_ebitda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('total_liabilities', models.FloatField(blank=True, null=True)),
                ('total_equity', models.FloatField(blank=True, null=True)),
                ('cash_and_equivalents', models.FloatField(blank=True, null=True)),
                ('short_term_debt', models.FloatField(blank=True, null=True)),
                ('long_term_debt', models.FloatField(blank=True, null=True)),
                ('accounts_receivable', models.FloatField(blank=True, null=True)),
                ('inventories', models.FloatField(blank=True, null=True)),
                ('retained_earnings', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('operating_cash_flow', models.FloatField(blank=True, null=True)),
                ('investing_cash_flow', models.FloatField(blank=True, null=True)),
                ('financing_cash_flow', models.FloatField(blank=True, null=True)),
                ('free_cash_flow', models.FloatField(blank=True, null=True)),
                ('capital_expenditures', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.stock')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('gross_profit', models.FloatField(blank=True, null=True)),
                ('operating_income', models.FloatField(blank=True, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('ebitda', models.FloatField(blank=True, null=True)),
                ('operating_expenses', models.FloatField(blank=True, null=True)),
                ('cost_of_revenue', models.FloatField(blank=True, null=True)),
                ('interest_expense', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SharePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikace.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
